schema_version: 1

context:
  version: "1.2.0"

package:
  name: aqua-core
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/aqua-core/aqua_core-${{ version }}.tar.gz
  sha256: 41e7973b94a65285ace3ebe72d6cdf4c2def523000744e589ccaea71200c0c3b

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - aqua = aqua.core.console.main:main

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.3
  run:
    - python <3.15
    - eccodes >=2.41.0
    - netcdf4
    - hdf5
    - h5py >=3.12.1
    - astropy-healpix
    - boto3
    - cartopy >=0.24.1
    - cdo >=2.5.0,<2.6.1
    - cfgrib
    - dask
    - distributed
    - fastparquet
    - filelock
    - gcsfs
    - icechunk
    - intake >=2.0.9
    - intake-xarray >=2.0.0
    - jinja2
    - kerchunk
    - matplotlib-base
    - metpy
    - numpy
    - pandas >=3.0.0
    - pypdf
    - pyyaml
    - regionmask
    - ruamel.yaml
    - scipy
    - seaborn
    - smmregrid ==0.1.6
    - xarray >=2025.12.0
    - zarr >=3.0

tests:
  - python:
      imports:
        - aqua
      pip_check: true
  - script:
      - aqua --help

about:
  homepage: https://github.com/DestinE-Climate-DT/AQUA/
  repository: https://github.com/DestinE-Climate-DT/AQUA/
  documentation: https://aqua.readthedocs.io/en/latest/index.html
  summary: AQUA; a model evaluation framework for high-resolution climate model simulations
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - oloapinivad
